apiVersion: v1
kind: ConfigMap
metadata:
  name: django-config
  namespace: django-app
data:
  DJANGO_DEBUG: "false"
  DJANGO_ALLOWED_HOSTS: "*"
  DB_HOST: "postgres-service"
  DB_PORT: "5432"
  DB_NAME: "django"
  DB_USER: "django"
