apiVersion: v1
kind: Secret
metadata:
  name: django-secrets
  namespace: django-app
type: Opaque
stringData:
  DJANGO_SECRET_KEY: "replace-with-secure-key-in-production"
  DB_PASSWORD: "passwordvasanth"
